apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-demo
  template:
    metadata:
      labels:
        app: backend-demo
    spec:
      containers:
      - name: backend-demo
        image: ghcr.io/renederum/backend-demo:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: backend-demo-config
      imagePullSecrets:
      - name: ghcr-secret
